version: '3.9'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql-slow-logs:/var/log/mysql/
    command: --slow-query-log=ON --log-output=FILE --slow-query-log-file=/var/log/mysql/slow-query.log --long-query-time=2
  
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.17.15
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat/filebeat.graylog.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./mysql-slow-logs:/var/app/log
    profiles:
      - manual
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ### GRAYLOG2

  mongo:
    image: mongo:5.0.13
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  
  graylog:
    image: graylog/graylog:5.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # BEATS
      - "5044:5044/tcp"
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
  
networks:
  graylog:
    driver: bridge
